# 测试配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://144.34.224.28:3306/my_db
    username: yuanrun
    password: 041365frk
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 144.34.224.28
    port: 6379
    timeout: 5000
    password: 041365frk
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://144.34.224.28:9200
    username: yuanrun
    password: 123456